require: rubocop-rspec
AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'activerecord-pretty-comparator.gemspec'
    - 'lib/activerecord-pretty-comparator.rb'
    - 'vendor/**/*'
  RespectGitIgnore: true
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4

RSpec/ExampleLength:
  Max: 6

Metrics/BlockLength:
  Exclude:
    - spec/*.rb
