name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test on ${{ matrix.activerecord_version }} and Ruby ${{ matrix.ruby_version }}
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
        activerecord_version:
          - "activerecord_7.2"
          - "activerecord_7.1"
          - "activerecord_7.0"
          - "activerecord_6.1"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: Bundle install
        run: bundle install
      - name: Setup activerecord
        run: bundle exec appraisal install
      - name: Test with ${{ matrix.activerecord_version }}
        run: bundle exec appraisal ${{ matrix.activerecord_version }} rspec
